// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYChR3WjFShFFKxka92co0Zk6noDpURdk',
    appId: '1:716589986175:web:c48f0056de0f9c54ca2a4a',
    messagingSenderId: '716589986175',
    projectId: 'babiesshop987',
    authDomain: 'babiesshop987.firebaseapp.com',
    storageBucket: 'babiesshop987.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo5CZpjoZpmrS55xNIr4niCdO8hFzrHnE',
    appId: '1:716589986175:android:83b7c5ede176c12aca2a4a',
    messagingSenderId: '716589986175',
    projectId: 'babiesshop987',
    storageBucket: 'babiesshop987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMZy5VGRui4tzpJ0ym5C-v5kByvp7BQs0',
    appId: '1:716589986175:ios:e7e9ae18cbc512e6ca2a4a',
    messagingSenderId: '716589986175',
    projectId: 'babiesshop987',
    storageBucket: 'babiesshop987.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMZy5VGRui4tzpJ0ym5C-v5kByvp7BQs0',
    appId: '1:716589986175:ios:e7e9ae18cbc512e6ca2a4a',
    messagingSenderId: '716589986175',
    projectId: 'babiesshop987',
    storageBucket: 'babiesshop987.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYChR3WjFShFFKxka92co0Zk6noDpURdk',
    appId: '1:716589986175:web:1d139d068c362eddca2a4a',
    messagingSenderId: '716589986175',
    projectId: 'babiesshop987',
    authDomain: 'babiesshop987.firebaseapp.com',
    storageBucket: 'babiesshop987.firebasestorage.app',
  );
}
